### ISSUE TITLE
common.css is missing

### ISSUE THREAD

**Issue by Windkracht8** [tborychowski/elastic-dark#1]
Hi, love the skin. A minor thing I run into when installing it. It will try to look for common.css in the elastic-dark root folder. It's not there resulting in a 404 and missing styling. I've linked the commons.css from the classic skin and it works perfectly.

**Comment by tborychowski** [comment]
That's weird. This line should handle this:
https://github.com/tborychowski/elastic-dark/blob/94e2c72288ac3aa9607601b490370c1808250b18/meta.json#L6

Which version of RC do you use?

**Comment by Windkracht8** [comment]
Sorry to have bothered you, it has resolved. I've updated RC to the latest, or maybe I just needed to clear my browser cache properly.
