### ISSUE TITLE
TinyMCE editor

### ISSUE THREAD

**Issue by Windkracht8** [tborychowski/elastic-dark#2]
In the readme you mention that the TinyMCE editor would need an ugly hack, I'm not sure if this is pretty enough, but this is what I am using now:
Copy the css from the TinyMCE oxide-dark skin into a css in the elastic-dark skin.
Then make TinyMCE use that css by adding this js:
var rcmail_editor_settings = {
        content_css: "/skins/elastic-dark/styles/tinymce.css"
};
If you like it I can create a pull request for this.

**Comment by tborychowski** [comment]
If it works, yes, please do!

**Comment by Windkracht8** [comment]
It works. But I do not have permission to create a branch here.
The changes are small, it's one line in templates/includes/layout.html:
<script>var rcmail_editor_settings = {content_css: "/skins/elastic-dark/styles/tinymce.css"};</script>
And then add tinymce.css (attached) to styles directory.
[tinymce.css.txt](https://github.com/tborychowski/elastic-dark/files/5772835/tinymce.css.txt)

**Comment by tborychowski** [comment]
Thanks @Windkracht8 ,
That's committed now.
(I tweaked the background color a bit, to match the dark to rest of the UI).

<img width="1037" alt="Screenshot 2021-01-06 at 10 42 25" src="https://user-images.githubusercontent.com/392513/103759605-e7473d00-500b-11eb-9270-9082f9a57cd0.png">

**Comment by Windkracht8** [comment]
Great!
