### ISSUE TITLE
Publish via Composer for easy install

### ISSUE THREAD

**Issue by Windkracht8** [tborychowski/elastic-dark#3]
If you could publish the skin on https://packagist.org it would make installing much easier, just add it to composer.json and then have it automatically update along with other extensions. Packagist can automatically update from Github, so it's only an initial setup.

**Comment by tborychowski** [comment]
Thank you for this tip!
It's added now: https://packagist.org/packages/tborychowski/elastic-dark

Let me know if you have any suggestions (e.g. to `composer.json`) to make it more discoverable :-)
(I have 0 experience with php packages)

**Comment by Windkracht8** [comment]
Could you lower the PHP version to match roundcube (>=5.4)?
Or drop it? (there is no PHP code in this package)
