### ISSUE TITLE
Switch a message view to light elastic

### ISSUE THREAD

**Issue by Windkracht8** [tborychowski/elastic-dark#4]
For some html emails the dark skin makes it difficult to read the email. A toggle to switch the message view to the light (default) elastic skin would be nice to make it easier to read.
I have a working prototype for this, if you are interested in this I will clean it up a bit and share the code.

**Comment by tborychowski** [comment]
Yes, please. That would be great.

**Comment by Windkracht8** [comment]
[layout.html.diff.txt](https://github.com/tborychowski/elastic-dark/files/5841848/layout.html.diff.txt)
[message.html.txt](https://github.com/tborychowski/elastic-dark/files/5841849/message.html.txt)
[darklighttoggle.js.txt](https://github.com/tborychowski/elastic-dark/files/5841872/darklighttoggle.js.txt)

The text Light and Dark are now hardcoded, to translate that into all available languages was a bit too much for me.

**Comment by tborychowski** [comment]
That's added now, thanks for your contribution!
