### ISSUE TITLE
Feature Request: Light/Dark Toggle default

### ISSUE THREAD

**Issue by metalcated** [tborychowski/elastic-dark#5]
Allow in settings to remember the Light mode toggle as a default setting. I personally prefer the white display for messages but dark for everything else. Nice work regardless. :)

**Comment by tborychowski** [comment]
Ha, if I only knew how! :-)
Not even sure if a "skin" can add a setting option.
But I think I can store the setting in the browser, so once you change the mode - it will persist (until you clean browser's cache).

**Comment by metalcated** [comment]
Nice! That was quick man! And yes that was what I was going to suggest
next. ;-)
