### ISSUE TITLE
Sidebar button Text missing

### ISSUE THREAD

**Issue by gotspatel** [tborychowski/elastic-dark#6]
How to enable the button Texts in Elastic-dark Theme

**Comment by tborychowski** [comment]
Hi,

You'd have to modify the css:
- remove this line: https://github.com/tborychowski/elastic-dark/blob/master/styles/styles-dark.css#L405 to revert the width of the menu to the original
- remove this line: https://github.com/tborychowski/elastic-dark/blob/master/styles/styles-dark.css#L409 to show the labels

(I think this is the right css. I cannot verify it as I don't use RC anymore).

**Comment by gotspatel** [comment]
Hi,

Many thanks for the reply and workaround.

But unfortunately it is not working and messingup the layout completely.

Regards,


Gautam Patel
On 19/04/2021 05:57:34 PM, Tom ***@***.***> wrote:
Hi,
You'd have to modify the css:
* remove this line: https://github.com/tborychowski/elastic-dark/blob/master/styles/styles-dark.css#L405 [https://github.com/tborychowski/elastic-dark/blob/master/styles/styles-dark.css#L405] to revert the width of the menu to the original
* remove this line: https://github.com/tborychowski/elastic-dark/blob/master/styles/styles-dark.css#L409 [https://github.com/tborychowski/elastic-dark/blob/master/styles/styles-dark.css#L409] to show the labels
(I think this is the right css. I cannot verify it as I don't use RC anymore).

**Comment by tborychowski** [comment]
ok, I tested it again. You also need to remove this line:
https://github.com/tborychowski/elastic-dark/blob/025201f605d817f6ff117ee7ce8910aa0b7511ba/styles/styles-dark.css#L408


that reverts almost all changes that I've added, and it will look like this:
<img width="114" alt="Screenshot 2021-04-20 at 10 11 34" src="https://user-images.githubusercontent.com/392513/115370337-e011fc80-a1c0-11eb-918e-1899868cee2b.png">

Bear in mind that this was tested on v1.5beta (but the css hasn't changed that much, so v1.4 should work too).

**Comment by gotspatel** [comment]
Thank you It works.

Sorry to bug you again but how to enable side panel logo display.

Regards,

Gautam Patel
On 20/04/2021 02:41:07 PM, Tom ***@***.***> wrote:
ok, I tested it again. You also need to remove this line:
https://github.com/tborychowski/elastic-dark/blob/025201f605d817f6ff117ee7ce8910aa0b7511ba/styles/styles-dark.css#L408 [https://github.com/tborychowski/elastic-dark/blob/025201f605d817f6ff117ee7ce8910aa0b7511ba/styles/styles-dark.css#L408]

**Comment by tborychowski** [comment]
Remove this line:

https://github.com/tborychowski/elastic-dark/blob/025201f605d817f6ff117ee7ce8910aa0b7511ba/styles/styles-dark.css#L406

**Comment by gotspatel** [comment]
Many thanks it works now
On 20/04/2021 08:32:29 PM, Tom ***@***.***> wrote:
Remove this line:
https://github.com/tborychowski/elastic-dark/blob/025201f605d817f6ff117ee7ce8910aa0b7511ba/styles/styles-dark.css#L406 [https://github.com/tborychowski/elastic-dark/blob/025201f605d817f6ff117ee7ce8910aa0b7511ba/styles/styles-dark.css#L406]
