### ISSUE TITLE
Logout button and login form logos/links

### ISSUE THREAD

**Issue by Nelnamara** [tborychowski/elastic-dark#7]
Is there a spot in the CSS I can get the logout button back?

Also looking to get the login screen items to display, is the background color making the base skin items?  I am not well versed poking at CSS.  I can say your stylesheet is 1000 time cleaner than the base elastic CSS.  Alas I keep running into the wrong thing.
[img]https://i.imgur.com/rdAuQJ5.png[/img]
[img]https://i.imgur.com/U8ZmkX2.png[/img]

**Comment by tborychowski** [comment]
logout wasn't meant to be hidden 🤔 
they must have changed something in the original skin...
This block is my only change to the original css:
https://github.com/tborychowski/elastic-dark/blob/025201f605d817f6ff117ee7ce8910aa0b7511ba/styles/styles-dark.css#L403-L411

try removing it and see if it helps.

as for the login screen, it may not only be the css, but the template that I modified :-)
so try removing this file: https://github.com/tborychowski/elastic-dark/blob/v1.5-beta/templates/login.html
to get the original elastic login.

Sorry, but I won't be able to support you more on this, as I stopped using RC and have neither time nor resources to even set this up again (to test).

**Comment by Nelnamara** [comment]
I just stumbled across that the spacing was just pushing the button below the threshold.... I was playing with the margin and set it to like 30 instead of 10 and it popped back above the bottom border

#taskmenu a {
    width: 40px;
    height: 40px;
    border-radius: 50%;
    margin: 8px 0 30px 0;

**Comment by porkserver** [comment]
Thanks for the pointers.  this got me on the right track it seems!

**Comment by Nelnamara** [comment]
Thanks for the pointers. this got me on the right track it seems!
I will fork this with my edits.
